# Clase 10

## Ejercicio 1.0 

In [2]:
import numpy as np

# Ejercicio 1.1

Repaso Arrays

In [3]:
#Array unidimensional
array1 = np.array([1,2,3,4])
array2 = np.array([5,6,7,8])

print(array1)

[1 2 3 4]


In [4]:
type(array1)

numpy.ndarray

In [5]:
print(array1 + array2)

[ 6  8 10 12]


In [6]:
print(array2 / array1)

[5.         3.         2.33333333 2.        ]


In [7]:
#Podemos crear una matriz 2 x 2
matriz1= np.array([
    [1, 2],
    [3, 4]
])

print(matriz1)

[[1 2]
 [3 4]]


In [8]:
#Podemos crear una matriz 2 x 4
matriz2= np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

print(matriz2)

[[1 2 3 4]
 [5 6 7 8]]


In [9]:
#Podemos crear una matriz 4 x 3
matriz3= np.array([
    [1, 2, 3],
    [5, 6, 7],
    [1, 6, 8],
    [0, 5, 7]
])

print(matriz3)

[[1 2 3]
 [5 6 7]
 [1 6 8]
 [0 5 7]]


# Ejercicio 1.2

operaciones con matrices

In [11]:
matrizA = np.array([
    [1, 2],
    [3, 4]
])

matrizB= np.array([
    [5, 6],
    [7, 8]
])

print(matrizA)
print("--------")
print(matrizB)

[[1 2]
 [3 4]]
--------
[[5 6]
 [7 8]]


In [13]:
#producto Matricial

matriz_producto = np.matmul(matrizA, matrizB)
print(matriz_producto)

[[19 22]
 [43 50]]


In [19]:
#Matriz transpuesta
matriz_originalA= np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]                          
])

print("Matriz original \n", matriz_originalA)
print("----------------------------------")
matriz_transpuesta = np.transpose(matriz_originalA)
print("Matriz transpuesta \n",matriz_transpuesta)

Matriz original 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
----------------------------------
Matriz transpuesta 
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [20]:
# Calculo del determinante
determinanteA = np.linalg.det(matrizA)
print("El determinante es:\n", determinanteA)

El determinante es:
 -2.0000000000000004
